# Generated by Django 4.1.4 on 2022-12-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='student',
        ),
    ]
