FROM python:3.9

WORKDIR /belajar/app/


copy . /belajar/app/
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

# copy project
COPY . .

CMD [ "python", "manage.py", "runserver", "0.0.0.0.800" ]